### PR TITLE
fix: return correct stack for local/global vars and add stack tests

### LINKED ISSUE #54: Look into using CallersFrames instead of Callers/FuncForPC
I came across some issues that suggested CallersFrames is preferred over how we're currently getting stack traces. This may not apply to us but we should make sure of it. For reference:
- https://github.com/cockroachdb/cockroach/issues/17770
- https://github.com/golang/go/issues/19426

### PR DESCRIPTION
**Pull request by morningvera**
closes #54

### CODE REVIEW

File: eris.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func wrap(err error, msg string) error {
 
 	// callers(4) skips this method, Wrap(f), stack.callers, and runtime.Callers
 	stack := callers(4)
-	frame := caller(4)
+	frame := caller(3)
```
Comment (morningvera) [inline eris.go]: The skip value has slightly different meanings for `callers` and `caller` so this was a bug. The wrap frames are now correct again.

File: eris.go [hunk 2]
```diff
@@ -60,6 +60,9 @@ func wrap(err error, msg string) error {
 				msg:    e.msg,
 				stack:  stack,
 			}
+		} else {
+			// insert the frame into the stack
```
Comment (morningvera) [inline eris.go]: This was also a bug. We were previously adding wrap frames to global stacks (so if you printed a global error without modification, it would have these random wrap layers on it that were coming from previous wrap calls).

File: examples/logging/example.go [hunk 3]
```diff
@@ -12,17 +12,17 @@ import (
 
 var (
 	// global error values can be useful when wrapping errors or inspecting error types
-	ErrInternalServer = eris.New("error internal server")
+	errInternalServer = eris.New("error internal server")
```
Comment (morningvera) [inline examples/logging/example.go]: Go report was complaining that we didn't comment these exported types, should be fixed now though

File: stack.go [hunk 4]
```diff
@@ -65,37 +65,27 @@ type frame uintptr
...
-		name = name[i+1:]
-		file, line := fn.FileLine(pc)
-
-		frame = StackFrame{
-			Name: name,
-			File: file,
-			Line: line,
-		}
-	}
+	frames := runtime.CallersFrames([]uintptr{pc})
```
Comment (morningvera) [inline stack.go]: The golang team recommends using `CallersFrames` instead of `FuncForPC`

File: eris_test.go [hunk 5]
```diff
@@ -260,40 +260,35 @@ func TestErrorFormatting(t *testing.T) {
...
-		name = name[i+1:]
-		file, line := fn.FileLine(pc)
+func getFrames(pc []uintptr) []eris.StackFrame {
+	var stackFrames []eris.StackFrame
+	if len(pc) == 0 {
+		return stackFrames
+	}
 
-		frame := eris.StackFrame{
+	frames := runtime.CallersFrames(pc)
```
Comment (sum2000) [inline eris_test.go]: Is this function faster? what advanatage does it have over previous implementation?

File: stack.go (hunk 4 above)
Comment (sum2000) [reply stack.go]: do you know why? or can you link to the recommendation?

File: stack_test.go [hunk 6]
```diff
@@ -0,0 +1,126 @@
+package eris_test
```
Comment (sum2000) [inline stack_test.go]: 👍 👍

File: eris.go (hunk 1 above)
Comment (morningvera) [reply eris.go]: it's tested now so it'll be more difficult to break it. i'll add a comment too though

File: stack.go (hunk 4 above)
Comment (morningvera) [reply stack.go]: we have an issue for it #54

File: eris_test.go (hunk 5 above)
Comment (morningvera) [reply eris_test.go]: see #54 (and also https://golang.org/pkg/runtime/#Callers)
