### PR TITLE
fix: add helper methods to show correct trace in sentry

### LINKED ISSUE #83: Missing error chain trace in Sentry
When logging to Sentry, error chain trace is missing. Text representation of wrapped errors is there, but no `File:Location` trace.
Using provided example:
```
go run examples/sentry/example.go -dsn=<Valid Sentry DSN>
```
Results in Sentry FULL mode:
```
EXCEPTION(most recent call first)

*eris.rootError
test
*eris.wrapError
wrap 1: test
*eris.wrapError
wrap 2: wrap 1: test
*eris.wrapError
wrap 3: wrap 2: wrap 1: test

example.go in main at line 54
	})
	if initErr != nil {
		log.Fatalf("failed to initialize Sentry: %v", initErr)
	}
	sentry.CaptureException(err)
	sentry.Flush(time.Second * 5)
}
```
Results in Sentry RAW mode:
```
EXCEPTION(most recent call first)

*eris.wrapError: wrap 3: wrap 2: wrap 1: test
  File "example.go", line 54, in main
    sentry.CaptureException(err)
```

### PR DESCRIPTION
**Pull request by sum2000**
closes #83

### CODE REVIEW

File: eris.go [hunk 1]
```diff
@@ -140,13 +140,17 @@ func Cause(err error) error {
 
 // StackFrames returns the trace of an error in the form of a program counter slice.
 // Use this method if you want to pass the eris stack trace to some other error tracing library.
+// Currently this method is for testing rootError and wrapError StackFrames() method only.
```
Comment (morningvera) [inline eris.go:143]: Is this comment necessary? Seems like it could still be useful for some users even apart from Sentry

File: eris.go [hunk 2]
```diff
@@ -177,6 +181,12 @@ func (e *rootError) Unwrap() error {
 	return e.ext
 }
 
+// StackFrames returns the trace of a root error in the form of a program counter slice.
+// This method is currently called by external error tracing library (sentry).
```
Comment (morningvera) [inline eris.go:185]: Super minor but I suggest capitalizing Sentry here and below to make it more clear that it's some other library

File: eris.go (hunk 1 above)
Comment (sum2000) [reply eris.go:143]: I wanted to denote that it is not part of the core library but still usable
